[project]
name = "leplayground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lerobot>=0.5.1",
    "h5py>=3.11",
    "opencv-python>=4.9",
    "uvicorn>=0.49.0",
    "fastapi>=0.136.3",
    "msgpack>=1.1.2",
    "websockets>=16.0",
]
